### ISSUE TITLE
TypeError: (e.adapter || a.adapter) is not a function for locally built copy

### ISSUE THREAD

**Issue by thephez** [dashevo/js-dash-sdk#154]
## Expected Behavior

Project can be built and used on my own machine

## Current Behavior

Following error returned when trying to use DAPI endpoints:
```
TypeError: (e.adapter || a.adapter) is not a function
    at e.exports (/dashevo/DashJS/dist/dash.min.js:31:643544)
    at async e.exports [as requestJsonRpc] (/dashevo/DashJS/dist/dash.min.js:24:587249)
    at async e.exports.request (/dashevo/DashJS/dist/dash.min.js:24:310070)
    at async o.getSimplifiedMNListDiff (/dashevo/DashJS/dist/dash.min.js:31:640284)
    at async o.updateMasternodeList (/dashevo/DashJS/dist/dash.min.js:31:640110)
    at async o.getSimplifiedMNList (/dashevo/DashJS/dist/dash.min.js:31:639937)
    at async e.exports.getLiveAddress (/dashevo/DashJS/dist/dash.min.js:31:640775)
    at async e.exports.request (/dashevo/DashJS/dist/dash.min.js:24:309883)
```

## Possible Solution

:shrug: 

## Steps to Reproduce (for bugs)

1. Clone repo and checkout master branch
2. `npm ci`
3. `npm run build`
4. `node connect.js` where connect.js is a file in the root of the repo containing:

``` js
const Dash = require('./dist/dash.min.js');

const client = new Dash.Client();

client.getDAPIClient().core.getBestBlockHash()
    .then((response) => console.log(response))
    .catch((e) => console.error(e));
```

## Your Environment

* Version used: Current `master` branch (0.16)
* Environment name and version (e.g. Chrome 39, node.js 5.4): nodejs 12.16.2
* Operating System and version (desktop, server, or mobile): Linux Mint

**Comment by Alex-Werner** [comment]
Hey @thephez, 

The File in `/dist` is intended for web usage (see webpack.config.json). 
What you want to do by running `node` is to call `/build/index.js' file instead. 
Also because the logic for browser / node is specified in package.json, doing just `const Dash = require('.');` will actually works ^.^' 

I suggest `const Dash = require('./build/index.js');`

**Comment by thephez** [comment]
@Alex-Werner Thanks :+1: 
`const Dash = require('./build/index.js');` doesn't work (that file doesn't exist in my build folder), but `const Dash = require('.');` does work for me.
