### ISSUE TITLE
Registering a name throws error: Cannot read property 'isDocumentDefined' of null

### ISSUE THREAD

**Issue by dashameter** [dashevo/js-dash-sdk#175]
Registering a name throws error:

```js
Something went wrong:
 TypeError: Cannot read property 'isDocumentDefined' of null
    at DocumentFactory.create (node_modules/@dashevo/dpp/lib/document/DocumentFactory.js:42:23)
    at DocumentFacade.create (node_modules/@dashevo/dpp/lib/document/DocumentFacade.js:43:25)
    at Platform.<anonymous> (node_modules/dash/build/src/SDK/Client/Platform/methods/documents/create.js:62:56)
    at step (node_modules/dash/build/src/SDK/Client/Platform/methods/documents/create.js:33:23)
    at Object.next (node_modules/dash/build/src/SDK/Client/Platform/methods/documents/create.js:14:53)
    at fulfilled (node_modules/dash/build/src/SDK/Client/Platform/methods/documents/create.js:5:58)
```

To reproduce:

```js
const Dash = require('dash');
const axios = require('axios')

const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms))

const clientOpts = {
  network: 'evonet',
  dapiAddresses: ['127.0.0.1:3000'],
  wallet: {
    mnemonic: null, // this indicates that we want a new wallet to be generated
                    // if you want to get a new address for an existing wallet
                    // replace 'null' with an existing wallet mnemonic
  },
};

const client = new Dash.Client(clientOpts);

const createWallet = async () => {
  client.account = await client.getWalletAccount();

  const mnemonic = client.wallet.exportWallet();
  const address = client.account.getUnusedAddress();
  console.log('Mnemonic:', mnemonic);
  console.log('Unused address:', address.address);
  return address.address
};

const receiveFaucetDrop = async (address) => {
  await axios.get(`http://127.0.0.1:5050/drip/${address}`)
  
  let confirmedBalance = client.account.getConfirmedBalance()
  let unconfirmedBalance = client.account.getUnconfirmedBalance()
  
  console.log('confirmedBalance :>> ', confirmedBalance);
  console.log('unconfirmedBalance :>> ', unconfirmedBalance);
  
  while (confirmedBalance < 10000) {
    await sleep(100)
    
    confirmedBalance = client.account.getConfirmedBalance()
    unconfirmedBalance = client.account.getUnconfirmedBalance()
    
    console.log('confirmedBalance :>> ', confirmedBalance);
    console.log('unconfirmedBalance :>> ', unconfirmedBalance);
  }

} 

const createIdentity = async () => {
  console.log("Registering Identity..")
  
  const identity = await client.platform.identities.register()
  
  console.log('identity :>> ', identity);
  
  return identity
};


const registerName = async (identity) => {
  const platform = client.platform;

  const nameRegistration = await platform.names.register(
    'myFirstDashName.dash',
    { dashUniqueIdentityId: identity.getId() },
    identity,
  );

  console.log('nameRegistration :>> ', nameRegistration);
  
  return nameRegistration;
};

createWallet()
  .then((address) => receiveFaucetDrop(address))
  .then(()=> createIdentity())
  .then((identity) => registerName(identity))
  .catch((e) => console.error('Something went wrong:\n', e))
  .finally(() => client.disconnect());
```

**Comment by minhquangthan** [comment]
Do we have any plans to fix this bug? I can't create a name or submit document because of this.

**Comment by Alex-Werner** [comment]
This actually happen during times where testnet is reset and therefore contractID hardcoded are not able to fetch contract. 
The way to fix it is to provide the right apps id to dashJS. 
Working on improving the error so it better highlight what is going wrong.

**Comment by Alex-Werner** [comment]
This actually happen during times where testnet is reset and therefore contractID hardcoded are not able to fetch contract. 
The way to fix it is to provide the right apps id to dashJS. 
Working on improving the error so it better highlight what is going wrong.

**Comment by thephez** [comment]
@Alex-Werner Just deleted your duplicate comment

**Comment by dashameter** [comment]
retested successfully on v.20 with dashmate, closing issue
