### ISSUE TITLE
TypeError: error.metadata.get is not a function

### ISSUE THREAD

**Issue by dashameter** [dashevo/js-dash-sdk#195]
```
      const result = await platform.documents.broadcast(documentBatch, identity)
```

throws

```
TypeError: f.metadata.get is not a function
```

how to better inspect it than with:
```
    } catch (e) {
      console.dir(e, { depth: 100 })
}
```

This error happens only when running in the browser after nuxt build / webpack. Using `npm run local` I can create the document. Both times I'm using the same contractId, reading from the contract works fine, only submitting a document throws an error after the bundling.

**Comment by antouhou** [comment]
What version of the SDK is it?

**Comment by dashameter** [comment]
3.18.1

**Comment by shumkov** [comment]
@dashameter could you please provide a stack trace (with source map preferably).

**Comment by dashameter** [comment]
@shumkov 

the error seems to have changed to:

```
Error: Assertion failed
    at n (http://app.springboard.cash/_nuxt/ea4f48a.js:2:246161)
    at A.toBuffer (http://app.springboard.cash/_nuxt/ea4f48a.js:2:252346)
    at t.h.toCompact (http://app.springboard.cash/_nuxt/ea4f48a.js:2:199423)
    at l (http://app.springboard.cash/_nuxt/ea4f48a.js:2:837546)
    at sign (http://app.springboard.cash/_nuxt/ea4f48a.js:2:837594)
    at t.exports.signByPrivateKey (http://app.springboard.cash/_nuxt/ea4f48a.js:2:511405)
    at t.exports.sign (http://app.springboard.cash/_nuxt/ea4f48a.js:2:1268159)
    at Object.<anonymous> (http://app.springboard.cash/_nuxt/ea4f48a.js:2:1293454)
    at http://app.springboard.cash/_nuxt/ea4f48a.js:2:1292968
    at Object.next (http://app.springboard.cash/_nuxt/ea4f48a.js:2:1293073)
message: "Assertion failed"
```
[stack1.txt](https://github.com/dashevo/js-dash-sdk/files/6203742/stack1.txt)
[stack2.txt](https://github.com/dashevo/js-dash-sdk/files/6203741/stack2.txt)
[stack3.txt](https://github.com/dashevo/js-dash-sdk/files/6203740/stack3.txt)
[stack4.txt](https://github.com/dashevo/js-dash-sdk/files/6203739/stack4.txt)
[stack5.txt](https://github.com/dashevo/js-dash-sdk/files/6203737/stack5.txt)

**Comment by antouhou** [comment]
Should be fixed by https://github.com/dashevo/wallet-lib/pull/247

**Comment by antouhou** [comment]
We need to update js SDK first though

**Comment by antouhou** [comment]
My bad -  #246 and #247 fix another issue, https://github.com/dashevo/wallet-lib/issues/236, not this one. This one remains open, I work on it currently

**Comment by dashameter** [comment]
passed retest

**Comment by SamKirby22** [comment]
Triage sheet updated. Thanks
