### ISSUE TITLE
TypeError: Channel credentials must be a ChannelCredentials object

### ISSUE THREAD

**Issue by dashameter** [dashevo/js-dash-sdk#253]
Using the dash-sdk side I'm encountering this message now, not sure what caused it, but now I can't get rid of it anymore. Using it against a local dashmate node:

```
(node:58889) UnhandledPromiseRejectionWarning: TypeError: Channel credentials must be a ChannelCredentials object
    at new ChannelImplementation (node_modules/@grpc/grpc-js/build/src/channel.js:75:19)
    at new Client (node_modules/@grpc/grpc-js/build/src/client.js:61:36)
    at new ServiceClientImpl (node_modules/@grpc/grpc-js/build/src/make-client.js:58:5)
    at new CorePromiseClient (node_modules/@dashevo/dapi-grpc/clients/core/v0/nodejs/CorePromiseClient.js:71:19)
    at GrpcTransport.request (node_modules/@dashevo/dapi-client/lib/transport/GrpcTransport.js:53:20)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async CoreMethodsFacade.getStatus (node_modules/@dashevo/dapi-client/lib/methods/core/getStatusFactory.js:24:22)
```

**Comment by Alex-Werner** [comment]
Thank you for this report. 
We are looking at it ! 
In order to ensure our best assumptions, could you please confirm us which version of : 

- dashmate version
- sdk version (or whatever any client you are using, dapi-client / dapi-grpc)

In advance, thank you.

**Comment by dashameter** [comment]
appears fixed in updated sdk
